name: basicinfrapipeline
trigger:
- master

pool: infra pool
stages: 

#------------------Terraform install and init ---------------#

- stage: terraforminstall
  displayName: terraform initalizing
  jobs: 
  - job: terraform_install
    steps: 
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
  - job: terraform_init
    steps: 
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'akansha'
        backendAzureRmOverrideSubscriptionID: '03817a80-26ba-454c-abd9-ecfc35cb5cc5'
        backendAzureRmResourceGroupName: 'mohit_rg'
        backendAzureRmStorageAccountName: 'mystorage5512'
        backendAzureRmContainerName: 'mohit-conatiner'
        backendAzureRmKey: 'key.tfstate'
#--------------terraform validate and fmt ------------------#

- stage: validate
  displayName: terraform validating
  dependsOn:  terraforminstall
  jobs:
  - job: terraform_vaidate
    steps: 
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'

#--------------terrafrom plan ------------- #
- stage: terraform_plan
  dependsOn: validate 
  jobs:
  - job: plan
    steps: 
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'akansha'
        environmentAzureRmOverrideSubscriptionID: '03817a80-26ba-454c-abd9-ecfc35cb5cc5'


#----------terraform apply ---------#
- stage: apply
  displayName: terraform apply
  dependsOn: terraform_plan
  jobs:
  - job:
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'akansha'
        environmentAzureRmOverrideSubscriptionID: '03817a80-26ba-454c-abd9-ecfc35cb5cc5'